### PR TITLE
Implement custom settings through env params for NAV and Clients

### PR DESCRIPTION
**Pull request by tfenster**
This addition allows to set customNavSettings, customWinSettings and customWebSettings to set arbitray config settings for the NAV server instance, ClickOnce Windows Client and WebClient. The format is:
`<variablename>="<key1>=<value1>,<key2>=<value2>"`
e.g.
`customNavSettings="EnableDebbuging=true,ReportPDFFontEmbedding=false"`
In cases where the config setting doesn't exist, the script creates it. Setting or creating a config value is also shown in the log

Tested with 2017-cu5-de and 2018-rtm-de

### CODE REVIEW

**Comment by freddydk** [comment]
SetupClickOnce exists in all version folders, you have only modified the one in 100.
Today they are identical, but some at least the prereqs are different for some of the older versions (which is the reason for copying them out)
The Web Configuration should be done in SetupWebClient (which also is in the version folders) - SetupWebConfiguration should be left empty for override purposes.

**Comment by tfenster** [comment]
Yes, I wanted to get your feedback before copying to all folders. 

SetupWebClient vs. SetupWebConfiguration: As it is the same in all releases I thought it might make sense to put it in the central one instead of copying. But I'll move it. 2017 is the only release where we need to support web.config and navsettings.json, right? 2013 to 2016 is web.config only and 2018 navsettings.json only?

**Comment by freddydk** [comment]
Thanks
2017 is only web.config
2018 is only navsettings.json
There were some preview builds in between with both, but we are not going to rebuild those.

**Comment by tfenster** [comment]
ok, moved the parts around

**Comment by freddydk** [comment]
Merged, thanks Tobias

**Comment by fvet** [comment]
What would be the format to pass these customsettings via the additionalParameters? 

`New-CSideDevContainer -additionalParameters @("-e customNavSettings=ApiServicesEnabled=true")`

**Comment by freddydk** [comment]
Use new-navcontainer instead of new-csidedevcontainer.
New-csidedevcontainer is only there not to break people who has used that, you can see in the implementation that new-csidedevcontainer just calls new-navcontainer https://github.com/Microsoft/navcontainerhelper/blob/master/ContainerHandling/New-CSideDevContainer.ps1

**Pull request merged**
